[package]
name = "axalloc"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS global memory allocator"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/modules/axalloc"
documentation = "https://rcore-os.github.io/arceos/axalloc/index.html"

[features]
alloc-buddy = []
alloc-slab = []
alloc-basic-first_fit = []
alloc-basic-best_fit = []
alloc-basic-worst_fit = []
alloc-tlsf-rust = []
alloc-tlsf-c = []
default = ["alloc-tlsf-c"]

[dependencies]
cfg-if = "1.0"
log = "0.4"
spinlock = { path = "../../crates/spinlock" }
memory_addr = { path = "../../crates/memory_addr" }
allocator = { path = "../../crates/allocator" }
axerrno = { path = "../../crates/axerrno" }