[package]
name = "lazy_init"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Provides macros and methods to iterate over the fields of a tuple struct"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/crates/lazy_init"
documentation = "https://rcore-os.github.io/arceos/lazy_init/index.html"

[dependencies]
