[package]
name = "axdriver"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS device drivers"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/modules/axdriver"
documentation = "https://rcore-os.github.io/arceos/axdriver/index.html"

[features]
bus-mmio = ["driver_virtio?/bus-mmio"]
bus-pci = ["driver_virtio?/bus-pci"]
virtio = ["driver_virtio", "dep:axalloc", "dep:axhal", "dep:axconfig"]

# various types of drivers
virtio-blk = ["virtio", "driver_block", "driver_virtio/block"]
virtio-net = ["virtio", "dep:driver_net", "driver_virtio/net"]
virtio-gpu = ["virtio", "dep:driver_display", "driver_virtio/gpu"]
ramdisk = ["driver_block/ramdisk"]
# more device example: e1000 = ["driver_net/e1000"]

default = ["bus-mmio"]

[dependencies]
log = "0.4"
cfg-if = "1.0"
tuple_for_each = { path = "../../crates/tuple_for_each" }
driver_common = { path = "../../crates/driver_common" }
driver_block = { path = "../../crates/driver_block", optional = true }
driver_net = { path = "../../crates/driver_net", optional = true }
driver_display = { path = "../../crates/driver_display", optional = true }
driver_virtio = { path = "../../crates/driver_virtio", optional = true }
axalloc = { path = "../axalloc", optional = true }
axhal = { path = "../axhal", optional = true }
axconfig = { path = "../axconfig", optional = true }
